#!/bin/sh

# This is a compact version of junonia_bootstrap for easy copying into user
# scripts. For a fully commented, documented version of this script see
# https://github.com/fprimex/junonia/blob/master/junonia.sh
junonia_bootstrap () {
  JUNONIA_TARGET="$0"
  while [ -h "$JUNONIA_TARGET" ]; do
    JUNONIA_PATH="$(file -h "$JUNONIA_TARGET" | \
                    sed 's/^.*symbolic link to //')"
    if [ "$(echo "$JUNONIA_PATH" | cut -c -1)" = "/" ]; then
      JUNONIA_TARGET="$JUNONIA_PATH"
    else
      JUNONIA_TARGET="$(dirname $JUNONIA_TARGET)"
      JUNONIA_TARGET="$JUNONIA_TARGET/$JUNONIA_PATH"
    fi
  done
  JUNONIA_PATH="$(cd "$(dirname "$JUNONIA_TARGET")" && pwd -P)"
  JUNONIA_TARGET="$JUNONIA_PATH/$(basename $JUNONIA_TARGET)"
  if [ "$(basename "$JUNONIA_PATH")" = bin ]; then
    JUNONIA_PATH="$(dirname "$JUNONIA_PATH")"
  fi
}

prog () {
  exec $0 help
}

JUNONIA_CACHE=0
junonia_bootstrap
. "$JUNONIA_PATH/../../junonia"

junonia_run "$@"

