#!/bin/sh

# All functions are implemented in this one top level program script.

prog () {
  echo "-shared-arg: $1"
  echo
  echo 'Run `prog help` options and subcommands'
}

prog_sub1 () {
  echo "-shared-arg: $1"
  echo "-sub1-opt1:  $2"
}

prog_sub2 () {
  echo "-shared-arg: $1"
  echo "-POS1:       $2"
  echo "-sub2-opt1:  $3"
  echo "-sub2-opt2:  $4"
}

prog_sub1_sub11 () {
  echo "-shared-arg: $1"
  echo "-sub1-opt1:  $2"
  echo "-bool1:      $3"
  echo "-bool2:      $4"
  echo "-sub11-opt1: $5"
}

prog_sub1_sub12 () {
  echo "-shared-arg: $1"
  echo "-sub1-opt1:  $2"
  echo "-bool1:      $3"
  echo "-bool2:      $4"
  echo "-sub12 OPT1: $5"
}

# This is a compact version of junonia_bootstrap for easy copying into user
# scripts. For a fully commented, documented version of this script see
# https://github.com/fprimex/junonia/blob/master/junonia.sh
junonia_bootstrap () {
  JUNONIA_TARGET="$0"
  while [ -h "$JUNONIA_TARGET" ]; do
    JUNONIA_PATH=$(readlink "$JUNONIA_TARGET")
    if [ "$(echo "$JUNONIA_PATH" | cut -c -1)" = "/" ]; then
      JUNONIA_TARGET="$JUNONIA_PATH"
    else
      JUNONIA_TARGET="$(dirname $JUNONIA_TARGET)"
      JUNONIA_TARGET="$JUNONIA_TARGET/$JUNONIA_PATH"
    fi
  done
  JUNONIA_PATH="$(cd "$(dirname "$JUNONIA_TARGET")" && pwd -P)"
  JUNONIA_TARGET="$JUNONIA_PATH/$(basename $JUNONIA_TARGET)"
  if [ "$(basename "$JUNONIA_PATH")" = bin ]; then
    JUNONIA_PATH="$(dirname "$JUNONIA_PATH")"
  fi
}

JUNONIA_CACHE=0
junonia_bootstrap
. "$JUNONIA_PATH/../../junonia"

# Instead of relying on automatic discovery of documentation, point the run
# directly at the (non-automatic) documentation directory with runmd.
junonia_runmd "program_docs.md" "$@"

