#!/bin/sh

prog () {
  echo "-shared-arg: $1"
  echo
  echo 'Run `prog help` options and subcommands'
}

prog_sub1 () {
  echo "-shared-arg: $1"
  echo "-param1    : $2"
  echo "-sub1-opt1 : $3"
  echo "-bool1     : $4"
  echo "-bool2     : $5"
}

prog_sub2 () {
  echo "-shared-arg: $1"
  echo "-POS1:       $2"
  echo "-sub2-opt1:  $3"
  echo "-sub2-opt2:  $4"
}

spec='# Prog

# This program runs from a spec string. The spec string is printed when help is
# requested.

# Blank lines and lines starting with # are ignored when the program argument
# spec is processed. Lines with "# " at the very start have the "# " stripped
# when "help" is run.

prog
  # Argument shared by all subcommands
  -shared-arg SHARED=shared_default

  # Junonia metacommands will be inserted here

  # Subcommand with one option
  sub1
    PARAM1=p
    -sub1-opt1 OPT1
    # This option could be documented in a comment here.
    -bool1
    -bool2=false

  # This subcommand takes one positional parameter
  # and two options.
  sub2
    POS1
    -sub2-opt1 OPT1
    -sub2-opt2 OPT2
'

# If you don't care about commenting the program for the help command,
# then this is all that is really required for this spec:
# spec='
# prog
#   -shared-arg SHARED
#   sub1
#     -sub1-opt1 OPT1
#   sub2
#     POS1
#     -sub2-opt1 OPT1
#     -sub2-opt2 OPT2
# '

# This is a compact version of junonia_bootstrap for easy copying into user
# scripts. For a fully commented, documented version of this script see
# https://github.com/fprimex/junonia/blob/master/junonia.sh
junonia_bootstrap () {
  JUNONIA_TARGET="$0"
  while [ -h "$JUNONIA_TARGET" ]; do
    JUNONIA_PATH=$(readlink "$JUNONIA_TARGET")
    if [ "$(echo "$JUNONIA_PATH" | cut -c -1)" = "/" ]; then
      JUNONIA_TARGET="$JUNONIA_PATH"
    else
      JUNONIA_TARGET="$(dirname $JUNONIA_TARGET)"
      JUNONIA_TARGET="$JUNONIA_TARGET/$JUNONIA_PATH"
    fi
  done
  JUNONIA_PATH="$(cd "$(dirname "$JUNONIA_TARGET")" && pwd -P)"
  JUNONIA_TARGET="$JUNONIA_PATH/$(basename $JUNONIA_TARGET)"
  if [ "$(basename "$JUNONIA_PATH")" = bin ]; then
    JUNONIA_PATH="$(dirname "$JUNONIA_PATH")"
  fi
}

JUNONIA_CACHE=0
junonia_bootstrap
. "$JUNONIA_PATH/../../junonia"

junonia_runspec "$spec" "$@"

